#This goes hand-in-hand with the base-files of OE-Core. The file must
# be sorted before 'systemd.conf' becuase this attempts to create a file
# inside /var/log.
#
# Note: /run/lock is already created by legacy.conf (from systemd), so
# we do not create it here to avoid the "Duplicate line" warning.

d		/var/volatile/log		-	-	-	-
d		/var/volatile/tmp		1777	-	-
