set-if-missing boot_animation librescoot
set-if-matches bootargs console=ttymxc0,115200 console=ttymxc0,115200 loglevel=0 quiet systemd.show_status=false vt.global_cursor_default=0 boot.animation=${boot_animation}
set-always splashpos m,395
