# configuration file for Weston

[core]
#modules=xwayland.so,cms-colord.so
shell=fullscreen-shell.so
#gbm-format=xrgb2101010
require-input=false
idle-time=0

[shell]
background-image=/usr/share/weston/backgrounds/librescoot-splash.png
background-color=0xff000000
background-type=scale
panel-location=none

[screen-share]
command=/usr/bin/weston --backend=rdp-backend.so --shell=fullscreen-shell.so --no-clients-resize
