include conf/distro/include/fsl-imx-base.inc
include conf/distro/include/fsl-imx-preferred-env.inc

DISTRO = "librescoot-dbc"

DISTRO_NAME = "Librescoot"
DISTRO_CODENAME ?= "none"

DISTRO_FEATURES:remove = "directfb x11 zeroconf avahi 3g nfc bluetooth"
DISTRO_FEATURES:append = " opengl pam systemd usrmerge"

DISTRO_VERSION := "${LIBRESCOOT_VERSION}"

# Set default timezone to Europe/Berlin
DEFAULT_TIMEZONE = "Europe/Berlin"

BBMASK:append =  " ${@bb.utils.contains('BBFILE_COLLECTIONS', 'raspberrypi', '', 'recipes-kernel/linux/linux-raspberrypi_6.6.bbappend', d)}"
