#!/bin/sh

RATE_FILE="${PPP_RATE_FILE:-/run/librescoot/ppp-link-rate}"
PPPD="${PPPD:-/usr/sbin/pppd}"
STATE_DIR="${PPP_RATE_STATE_DIR:-/run/librescoot}"
RATE=250000

mkdir -p "$STATE_DIR"
rm -f "$STATE_DIR/ppp-link-disabled"

if [ -r "$RATE_FILE" ]; then
    RATE=$(cat "$RATE_FILE")
fi

case "$RATE" in
    250000|2500000) ;;
    *) RATE=250000 ;;
esac

exec "$PPPD" call uart-link "$RATE" nodetach
