confdir /etc/chrony/conf.d

pool de.pool.ntp.org iburst

refclock SHM 0 refid GPS precision 1e-1 offset 0.200 delay 0.2 poll 4 trust
refclock SHM 1 refid PPS precision 1e-7

sourcedir /etc/chrony/sources.d

makestep 1 -1
driftfile /var/lib/chrony/drift
rtcsync
allow 192.168.7.0/24
local stratum 1
logdir /var/log/chrony
